name: ecommerce_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  go_router: ^14.2.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
    - .env